patch -p1 < ste_patches/bionic.patch
patch -p1 < ste_patches/external_icu.patch
patch -p1 < ste_patches/system_core.patch
patch -p1 < ste_patches/system_vold.patch
patch -p1 < ste_patches/frameworks/av/001_ste_multimedia.patch
patch -p1 < ste_patches/frameworks/av/002_ste_audio.patch
patch -p1 < ste_patches/frameworks/native/001_ste_multimedia.patch
patch -p1 < ste_patches/frameworks/native/002_hwc_0.3.patch
patch -p1 < ste_patches/frameworks/native/003_misc_fix.patch
patch -p1 < ste_patches/hardware/libhardware/001_hwcomposer_0.3.patch
